### ISSUE TITLE
Transfer repository to HITS-SDBV

### ISSUE THREAD

**Issue by nwoetzel** [HITS-SDBV/nmtrypi-seek#1]
We would like to increase visibility of the project, continue development and for that like would like you to transfer ownership of the repo to https://github.com/HITS-SDBV

Could you please get in touch with the SDBV group at HITS?
Thanks, Nils

**Comment by aina1205** [comment]
I tried but failed with the error message from github:

You don’t have admin rights to HITS-SDBV

So maybe first you add me to be admin of HITS-SDBV and then remove me from admins after transfer? Or any better suggestion?

Regards
Lihua

**Comment by nwoetzel** [comment]
You will need to accept the invitation for the organization.

**Comment by aina1205** [comment]
Transfer is done.

regards, Lihua

**Comment by nwoetzel** [comment]
Thanks a lot.
